/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.27.5+k3s1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoCattleManagementv3ProjectStatus : Status is the most recently observed status of the project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoCattleManagementv3ProjectStatus {
    /// Conditions are a set of indicators about aspects of the project.
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<models::IoCattleManagementv3ProjectStatusConditionsInner>>,
    #[serde(rename = "monitoringStatus", skip_serializing_if = "Option::is_none")]
    pub monitoring_status: Option<Box<models::IoCattleManagementv3ProjectStatusMonitoringStatus>>,
    /// PodSecurityPolicyTemplateName is the pod security policy template associated with the project.
    #[serde(rename = "podSecurityPolicyTemplateId", skip_serializing_if = "Option::is_none")]
    pub pod_security_policy_template_id: Option<String>,
}

impl IoCattleManagementv3ProjectStatus {
    /// Status is the most recently observed status of the project.
    pub fn new() -> IoCattleManagementv3ProjectStatus {
        IoCattleManagementv3ProjectStatus {
            conditions: None,
            monitoring_status: None,
            pod_security_policy_template_id: None,
        }
    }
}

