/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.27.5+k3s1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_diff::SerdeDiff;

/// IoK8sApimachineryPkgApisMetaV1Patch : Patch is provided to give a concrete name and type to the Kubernetes PATCH request body.
/// Patch is provided to give a concrete name and type to the Kubernetes PATCH request body.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IoK8sApimachineryPkgApisMetaV1Patch {
    /// Patch data represented as a dictionary.
    Object(std::collections::HashMap<String, serde_json::Value>),
    /// Patch data represented as a list of dictionaries.
    Array(Vec<serde_json::Value>),
}

impl Default for IoK8sApimachineryPkgApisMetaV1Patch {
    fn default() -> Self {
        Self::Object(Default::default())
    }
}

