/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.27.5+k3s1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoK8sApimachineryPkgApisMetaV1Preconditions : Preconditions must be fulfilled before an operation (update, delete, etc.) is carried out.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoK8sApimachineryPkgApisMetaV1Preconditions {
    /// Specifies the target ResourceVersion
    #[serde(rename = "resourceVersion", skip_serializing_if = "Option::is_none")]
    pub resource_version: Option<String>,
    /// Specifies the target UID.
    #[serde(rename = "uid", skip_serializing_if = "Option::is_none")]
    pub uid: Option<String>,
}

impl IoK8sApimachineryPkgApisMetaV1Preconditions {
    /// Preconditions must be fulfilled before an operation (update, delete, etc.) is carried out.
    pub fn new() -> IoK8sApimachineryPkgApisMetaV1Preconditions {
        IoK8sApimachineryPkgApisMetaV1Preconditions {
            resource_version: None,
            uid: None,
        }
    }
}

